phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing zip and unzip...
      - apt-get update
      - apt-get install -y zip unzip

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Packaging the application...
      - zip -r cbmalalhueApp.zip ./dist/landing-page-angular17
      - echo Uploading ZIP to S3...
      - aws s3 cp cbmalalhueApp.zip s3://codepipeline-us-east-2-320386715850/cbmalalhueApp.zip
      - echo Downloading ZIP from S3...
      - aws s3 cp s3://codepipeline-us-east-2-320386715850/cbmalalhueApp.zip .
      - echo Extracting ZIP...
      - unzip cbmalalhueApp.zip -d extracted
      - echo Syncing to S3...
      - aws s3 sync extracted/ s3://cbmalalhue --acl public-read
