version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the project...
      - npm run build

post_build:
  commands:
    - echo Creating ZIP file and deploying to S3...
    - zip -r cbmalalhueApp.zip ./dist/landing-page-angular17
    - aws s3 cp cbmalalhueApp.zip s3://codepipeline-us-east-2-555005272417/cbmalalhueApp.zip
    - aws s3 cp s3://codepipeline-us-east-2-555005272417/cbmalalhueApp.zip .
    - unzip cbmalalhueApp.zip -d extracted
    - aws s3 sync extracted/ s3://cbmalalhue.cl --acl public-read
