export const ApiTag = {
  POST: 'post',
  POSTS: 'posts',
  COMPANIES: 'pages/?slug=company-',
  MEDIA: 'media',
  DIRECTORY: 'directory',
  MACHINES: 'machines',
  VOLUNTEERS: 'volunteers',
  CATEGORIES: 'categories',
  GALLERIES: 'nextgen-galleries',
  GALLERY: 'nextgen-gallery-images',
  CONTACT_FORMS: 'contact-forms',
  BANNERS_AND_PROMOTIONS: 'pages/?slug=banner-y-promociones',
  BANNER: 'pages/?slug=banner',
};
